//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Ayende Rahien")]
[assembly: CLSCompliant(true)]
[assembly: ComVisible(false)]
[assembly: AssemblyCopyright("Ayende Rahien(c) 2007")]
[assembly: AssemblyDescription("Rhino.Igloo")]
[assembly: AssemblyInformationalVersion("0.01.248")]
[assembly: AssemblyTitle("Rhino.Igloo")]
[assembly: AssemblyVersion("0.01.248")]


