//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        static Root_Query_Blog _root_query_Blog = new Root_Query_Blog();
        
        public static Root_Query_Blog Blog {
            get {
                return _root_query_Blog;
            }
        }
        
        public class Query_Blog<T1> : Query.QueryBuilder<T1>
         {
            
            public Query_Blog(string name, string assoicationPath) : 
                    base(name, assoicationPath) {
            }
            
            public Query_Blog(string name, string assoicationPath, bool backTrackAssoicationOnEquality) : 
                    base(name, assoicationPath, backTrackAssoicationOnEquality) {
            }
            
            public virtual Query.PropertyQueryBuilder<T1> Name {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<T1>("Name", temp);
                }
            }
            
            public virtual Query.QueryBuilder<T1> Id {
                get {
                    string temp = assoicationPath;
                    return new Query.QueryBuilder<T1>("Id", temp);
                }
            }
            
            public virtual Query_User<T1> Author {
                get {
                    string temp = assoicationPath;
                    temp = ((temp + ".") 
                                + "Author");
                    return new Query_User<T1>("Author", temp, true);
                }
            }
        }
        
        public class Root_Query_Blog {
            
            private string assoicationPath = "this";
            
            public virtual Query.PropertyQueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Blog> Name {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Blog>("Name", temp);
                }
            }
            
            public virtual Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Blog> Id {
                get {
                    string temp = assoicationPath;
                    return new Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Blog>("Id", temp);
                }
            }
            
            public virtual Query_User<NHibernate.Query.Generator.Tests.ActiveRecord.Blog> Author {
                get {
                    string temp = assoicationPath;
                    temp = ((temp + ".") 
                                + "Author");
                    return new Query_User<NHibernate.Query.Generator.Tests.ActiveRecord.Blog>("Author", temp, true);
                }
            }
        }
    }
    
    public partial class OrderBy {
        
        public partial class Blog {
            
            public static Query.OrderByClause Name {
                get {
                    return new Query.OrderByClause("Name");
                }
            }
        }
    }
}
