//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        static Root_Query_Cat _root_query_Cat = new Root_Query_Cat();
        
        static Root_Query_DomesticCat _root_query_DomesticCat = new Root_Query_DomesticCat();
        
        public static Root_Query_Cat Cat {
            get {
                return _root_query_Cat;
            }
        }
        
        public static Root_Query_DomesticCat DomesticCat {
            get {
                return _root_query_DomesticCat;
            }
        }
        
        public partial class Query_Cat<T1> : Query.QueryBuilder<T1>
         {
            
            public Query_Cat(string name, string associationPath) : 
                    base(name, associationPath) {
            }
            
            public Query_Cat(string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(name, associationPath, backTrackAssociationOnEquality) {
            }
            
            public virtual Query.QueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    return new Query.QueryBuilder<T1>("Id", temp);
                }
            }
        }
        
        public partial class Root_Query_Cat : Query_Cat<NHibernate.Query.Generator.Tests.ActiveRecord.Cat> {
            
            public Root_Query_Cat() : 
                    base("this", null) {
            }
        }
        public partial class Query_DomesticCat<T2> : Query_Cat<T2>
         {
            
            public Query_DomesticCat(string name, string associationPath) : 
                    base(name, associationPath) {
            }
            
            public Query_DomesticCat(string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(name, associationPath, backTrackAssociationOnEquality) {
            }
        }
        public partial class Root_Query_DomesticCat : Query_DomesticCat<NHibernate.Query.Generator.Tests.ActiveRecord.DomesticCat> {
            
            public Root_Query_DomesticCat() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class OrderBy {
    }
    
    public partial class ProjectBy {
    }
    
    public partial class GroupBy {
    }
}
