//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        static Root_Query_Comment _root_query_Comment = new Root_Query_Comment();
        
        public static Root_Query_Comment Comment {
            get {
                return _root_query_Comment;
            }
        }
        
        public class Query_Comment<T1> : Query.QueryBuilder<T1>
         {
            
            public Query_Comment(string name, string assoicationPath) : 
                    base(name, assoicationPath) {
            }
            
            public Query_Comment(string name, string assoicationPath, bool backTrackAssoicationOnEquality) : 
                    base(name, assoicationPath, backTrackAssoicationOnEquality) {
            }
            
            public virtual Query.PropertyQueryBuilder<T1> Author {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<T1>("Author", temp);
                }
            }
            
            public virtual Query.PropertyQueryBuilder<T1> Content {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<T1>("Content", temp);
                }
            }
            
            public virtual Query.QueryBuilder<T1> Id {
                get {
                    string temp = assoicationPath;
                    return new Query.QueryBuilder<T1>("Id", temp);
                }
            }
            
            public virtual Query_Post<T1> Post {
                get {
                    string temp = assoicationPath;
                    temp = ((temp + ".") 
                                + "Post");
                    return new Query_Post<T1>("Post", temp, true);
                }
            }
        }
        
        public class Root_Query_Comment {
            
            private string assoicationPath = "this";
            
            public virtual Query.PropertyQueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Comment> Author {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Comment>("Author", temp);
                }
            }
            
            public virtual Query.PropertyQueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Comment> Content {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Comment>("Content", temp);
                }
            }
            
            public virtual Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Comment> Id {
                get {
                    string temp = assoicationPath;
                    return new Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Comment>("Id", temp);
                }
            }
            
            public virtual Query_Post<NHibernate.Query.Generator.Tests.ActiveRecord.Comment> Post {
                get {
                    string temp = assoicationPath;
                    temp = ((temp + ".") 
                                + "Post");
                    return new Query_Post<NHibernate.Query.Generator.Tests.ActiveRecord.Comment>("Post", temp, true);
                }
            }
        }
    }
    
    public partial class OrderBy {
        
        public partial class Comment {
            
            public static Query.OrderByClause Author {
                get {
                    return new Query.OrderByClause("Author");
                }
            }
            
            public static Query.OrderByClause Content {
                get {
                    return new Query.OrderByClause("Content");
                }
            }
        }
    }
}
