//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        static Root_Query_WeirdClass _root_query_WeirdClass = new Root_Query_WeirdClass();
        
        public static Root_Query_WeirdClass WeirdClass {
            get {
                return _root_query_WeirdClass;
            }
        }
        
        public class Query_WeirdClass<T1> : Query.QueryBuilder<T1>
         {
            
            public Query_WeirdClass(string name, string assoicationPath) : 
                    base(name, assoicationPath) {
            }
            
            public Query_WeirdClass(string name, string assoicationPath, bool backTrackAssoicationOnEquality) : 
                    base(name, assoicationPath, backTrackAssoicationOnEquality) {
            }
            
            public virtual Query.PropertyQueryBuilder<T1> Department {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<T1>("Department", temp);
                }
            }
            
            public virtual Query.PropertyQueryBuilder<T1> Level {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<T1>("Level", temp);
                }
            }
        }
        
        public class Root_Query_WeirdClass {
            
            private string assoicationPath = "this";
            
            public virtual Query.PropertyQueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.WeirdClass> Department {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.WeirdClass>("Department", temp);
                }
            }
            
            public virtual Query.PropertyQueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.WeirdClass> Level {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.WeirdClass>("Level", temp);
                }
            }
        }
    }
    
    public partial class OrderBy {
        
        public partial class WeirdClass {
            
            public partial class Key {
                
                public static Query.OrderByClause Department {
                    get {
                        return new Query.OrderByClause("Department");
                    }
                }
                
                public static Query.OrderByClause Level {
                    get {
                        return new Query.OrderByClause("Level");
                    }
                }
            }
        }
    }
}
