//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class For {
        
        /// Query Builder for member Cat
        public static Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Cat> Cat {
            get {
                return new Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Cat>();
            }
        }
        
        /// Query Builder for member DomesticCat
        public static Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.DomesticCat> DomesticCat {
            get {
                return new Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.DomesticCat>();
            }
        }
    }
    
    public partial class Where {
        
        /// Where for member _root_Where_Cat
        static Root_Where_Cat _root_Where_Cat = new Root_Where_Cat();
        
        /// Where for member _root_Where_DomesticCat
        static Root_Where_DomesticCat _root_Where_DomesticCat = new Root_Where_DomesticCat();
        
        /// Where for member Cat
        public static Root_Where_Cat Cat {
            get {
                return _root_Where_Cat;
            }
        }
        
        /// Where for member DomesticCat
        public static Root_Where_DomesticCat DomesticCat {
            get {
                return _root_Where_DomesticCat;
            }
        }
        
        /// Where for member Where_Cat
        public partial class Where_Cat<T1> : Query.WhereClause<T1>
         {
            
            /// Where for member .ctor
            public Where_Cat(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// Where for member .ctor
            public Where_Cat(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// Where for member 
            public virtual Query.WhereClauseProperty<T1> subclass {
                get {
                    string temp = QpAssociationPath;
                    return new Query.WhereClauseProperty<T1>("subclass", temp);
                }
            }
            
            /// Where for member 
            public virtual Query.WhereClause<T1> Id {
                get {
                    string temp = QpAssociationPath;
                    return new Query.WhereClause<T1>("Id", temp);
                }
            }
        }
        
        /// Where for member Root_Where_Cat
        public partial class Root_Where_Cat : Where_Cat<NHibernate.Query.Generator.Tests.ActiveRecord.Cat> {
            
            /// Where for member .ctor
            public Root_Where_Cat() : 
                    base("this", null) {
            }
        }
        
        /// Where for member Where_DomesticCat
        public partial class Where_DomesticCat<T2> : Where_Cat<T2>
         {
            
            /// Where for member .ctor
            public Where_DomesticCat(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// Where for member .ctor
            public Where_DomesticCat(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// Where for member 
            public virtual Query.WhereClauseProperty<T2> Name {
                get {
                    string temp = QpAssociationPath;
                    return new Query.WhereClauseProperty<T2>("Name", temp);
                }
            }
        }
        
        /// Where for member Root_Where_DomesticCat
        public partial class Root_Where_DomesticCat : Where_DomesticCat<NHibernate.Query.Generator.Tests.ActiveRecord.DomesticCat> {
            
            /// Where for member .ctor
            public Root_Where_DomesticCat() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// Projection for member _root_Projection_Cat
        static Root_Projection_Cat _root_Projection_Cat = new Root_Projection_Cat();
        
        /// Projection for member _root_Projection_DomesticCat
        static Root_Projection_DomesticCat _root_Projection_DomesticCat = new Root_Projection_DomesticCat();
        
        /// Projection for member Cat
        public static Root_Projection_Cat Cat {
            get {
                return _root_Projection_Cat;
            }
        }
        
        /// Projection for member DomesticCat
        public static Root_Projection_DomesticCat DomesticCat {
            get {
                return _root_Projection_DomesticCat;
            }
        }
        
        /// Projection for member Projection_Cat
        public partial class Projection_Cat<T3> : Query.ProjectionEntity<T3>
         {
            
            /// Projection for member .ctor
            public Projection_Cat(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// Projection for member .ctor
            public Projection_Cat(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// Projection for member 
            public virtual Query.ProjectionClauseProperty<T3> subclass {
                get {
                    string temp = QpAssociationPath;
                    return new Query.ProjectionClauseProperty<T3>("subclass", temp);
                }
            }
            
            /// Projection for member 
            public virtual Query.ProjectionClausePropertyNumeric<T3> Id {
                get {
                    string temp = QpAssociationPath;
                    return new Query.ProjectionClausePropertyNumeric<T3>("Id", temp);
                }
            }
        }
        
        /// Projection for member Root_Projection_Cat
        public partial class Root_Projection_Cat : Projection_Cat<NHibernate.Query.Generator.Tests.ActiveRecord.Cat> {
            
            /// Projection for member .ctor
            public Root_Projection_Cat() : 
                    base("this", null) {
            }
        }
        
        /// Projection for member Projection_DomesticCat
        public partial class Projection_DomesticCat<T4> : Projection_Cat<T4>
         {
            
            /// Projection for member .ctor
            public Projection_DomesticCat(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// Projection for member .ctor
            public Projection_DomesticCat(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// Projection for member 
            public virtual Query.ProjectionClauseProperty<T4> Name {
                get {
                    string temp = QpAssociationPath;
                    return new Query.ProjectionClauseProperty<T4>("Name", temp);
                }
            }
        }
        
        /// Projection for member Root_Projection_DomesticCat
        public partial class Root_Projection_DomesticCat : Projection_DomesticCat<NHibernate.Query.Generator.Tests.ActiveRecord.DomesticCat> {
            
            /// Projection for member .ctor
            public Root_Projection_DomesticCat() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class OrderBy {
        
        /// OrderBy for member _root_OrderBy_Cat
        static Root_OrderBy_Cat _root_OrderBy_Cat = new Root_OrderBy_Cat();
        
        /// OrderBy for member _root_OrderBy_DomesticCat
        static Root_OrderBy_DomesticCat _root_OrderBy_DomesticCat = new Root_OrderBy_DomesticCat();
        
        /// OrderBy for member Cat
        public static Root_OrderBy_Cat Cat {
            get {
                return _root_OrderBy_Cat;
            }
        }
        
        /// OrderBy for member DomesticCat
        public static Root_OrderBy_DomesticCat DomesticCat {
            get {
                return _root_OrderBy_DomesticCat;
            }
        }
        
        /// OrderBy for member OrderBy_Cat
        public partial class OrderBy_Cat<T5> : Query.QueryPart
         {
            
            /// OrderBy for member .ctor
            public OrderBy_Cat(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// OrderBy for member .ctor
            public OrderBy_Cat(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// OrderBy for member 
            public virtual Query.OrderByClauseProperty<T5> subclass {
                get {
                    string temp = QpAssociationPath;
                    return new Query.OrderByClauseProperty<T5>("subclass", temp);
                }
            }
            
            /// OrderBy for member 
            public virtual Query.OrderByClauseProperty<T5> Id {
                get {
                    string temp = QpAssociationPath;
                    return new Query.OrderByClauseProperty<T5>("Id", temp);
                }
            }
        }
        
        /// OrderBy for member Root_OrderBy_Cat
        public partial class Root_OrderBy_Cat : OrderBy_Cat<NHibernate.Query.Generator.Tests.ActiveRecord.Cat> {
            
            /// OrderBy for member .ctor
            public Root_OrderBy_Cat() : 
                    base("this", null) {
            }
        }
        
        /// OrderBy for member OrderBy_DomesticCat
        public partial class OrderBy_DomesticCat<T6> : OrderBy_Cat<T6>
         {
            
            /// OrderBy for member .ctor
            public OrderBy_DomesticCat(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// OrderBy for member .ctor
            public OrderBy_DomesticCat(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// OrderBy for member 
            public virtual Query.OrderByClauseProperty<T6> Name {
                get {
                    string temp = QpAssociationPath;
                    return new Query.OrderByClauseProperty<T6>("Name", temp);
                }
            }
        }
        
        /// OrderBy for member Root_OrderBy_DomesticCat
        public partial class Root_OrderBy_DomesticCat : OrderBy_DomesticCat<NHibernate.Query.Generator.Tests.ActiveRecord.DomesticCat> {
            
            /// OrderBy for member .ctor
            public Root_OrderBy_DomesticCat() : 
                    base("this", null) {
            }
        }
    }
}
