//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
    }
    
    public partial class OrderBy {
    }
    
    public partial class Queries {
        
        /// Query for member AllCats
        public static string AllCats {
            get {
                return "AllCats";
            }
        }
    }
    
    public partial class ProjectBy {
    }
    
    public partial class GroupBy {
    }
}
