//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        /// <summary>
        /// Query helper for member Where.Istoric
        /// </summary>
        public static Root_Query_Istoric Istoric {
            get {
                return new Root_Query_Istoric();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.MesajIst
        /// </summary>
        public static Root_Query_MesajIst MesajIst {
            get {
                return new Root_Query_MesajIst();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_Istoric
        /// </summary>
        public partial class Query_Istoric<T1> : QueryBuilder<T1>
         {
            
            /// <summary>
            /// Query helper for member Query_Istoric..ctor
            /// </summary>
            public Query_Istoric(QueryBuilder<T1> parent, string name, string associationPath) : 
                    base(parent, name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_Istoric..ctor
            /// </summary>
            public Query_Istoric(QueryBuilder<T1> parent, string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(parent, name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_Istoric.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Name {
                get {
                    string temp = associationPath;
                    return new PropertyQueryBuilder<T1>(this, "Name", temp);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_Istoric.
            /// </summary>
            public virtual QueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    return new QueryBuilder<T1>(this, "Id", temp);
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_Istoric
        /// </summary>
        public partial class Root_Query_Istoric : Query_Istoric<NHibernate.Query.Generator.Tests.ActiveRecord.Istoric> {
            
            /// <summary>
            /// Query helper for member Root_Query_Istoric..ctor
            /// </summary>
            public Root_Query_Istoric() : 
                    base(null, "this", null) {
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_MesajIst
        /// </summary>
        public partial class Query_MesajIst<T2> : Query_Istoric<T2>
         {
            
            /// <summary>
            /// Query helper for member Query_MesajIst..ctor
            /// </summary>
            public Query_MesajIst(QueryBuilder<T2> parent, string name, string associationPath) : 
                    base(parent, name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_MesajIst..ctor
            /// </summary>
            public Query_MesajIst(QueryBuilder<T2> parent, string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(parent, name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_MesajIst.
            /// </summary>
            public virtual PropertyQueryBuilder<T2> Email {
                get {
                    string temp = associationPath;
                    return new PropertyQueryBuilder<T2>(this, "Email", temp);
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_MesajIst
        /// </summary>
        public partial class Root_Query_MesajIst : Query_MesajIst<NHibernate.Query.Generator.Tests.ActiveRecord.MesajIst> {
            
            /// <summary>
            /// Query helper for member Root_Query_MesajIst..ctor
            /// </summary>
            public Root_Query_MesajIst() : 
                    base(null, "this", null) {
            }
        }
    }
    
    public partial class OrderBy {
        
        /// <summary>
        /// Query helper for member OrderBy.Istoric
        /// </summary>
        public partial class Istoric {
            
            /// <summary>
            /// Query helper for member Istoric.Name
            /// </summary>
            public static OrderByClause Name {
                get {
                    return new OrderByClause("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member Istoric.Id
            /// </summary>
            public static OrderByClause Id {
                get {
                    return new OrderByClause("Id");
                }
            }
        }
        
        /// <summary>
        /// Query helper for member OrderBy.MesajIst
        /// </summary>
        public partial class MesajIst : Istoric {
            
            /// <summary>
            /// Query helper for member MesajIst.Email
            /// </summary>
            public static OrderByClause Email {
                get {
                    return new OrderByClause("Email");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// <summary>
        /// Query helper for member ProjectBy.Istoric
        /// </summary>
        public partial class Istoric {
            
            /// <summary>
            /// Query helper for member Istoric.Name
            /// </summary>
            public static PropertyProjectionBuilder Name {
                get {
                    return new PropertyProjectionBuilder("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member Istoric.Id
            /// </summary>
            public static NumericPropertyProjectionBuilder Id {
                get {
                    return new NumericPropertyProjectionBuilder("Id");
                }
            }
        }
        
        /// <summary>
        /// Query helper for member ProjectBy.MesajIst
        /// </summary>
        public partial class MesajIst : Istoric {
            
            /// <summary>
            /// Query helper for member MesajIst.Email
            /// </summary>
            public static PropertyProjectionBuilder Email {
                get {
                    return new PropertyProjectionBuilder("Email");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// <summary>
        /// Query helper for member GroupBy.Istoric
        /// </summary>
        public partial class Istoric {
            
            /// <summary>
            /// Query helper for member Istoric.Name
            /// </summary>
            public static NHibernate.Expression.IProjection Name {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Name");
                }
            }
        }
        
        /// <summary>
        /// Query helper for member GroupBy.MesajIst
        /// </summary>
        public partial class MesajIst : Istoric {
            
            /// <summary>
            /// Query helper for member MesajIst.Email
            /// </summary>
            public static NHibernate.Expression.IProjection Email {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Email");
                }
            }
        }
    }
}
