//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        /// Query for member _root_query_DerivedBlog2
        static Root_Query_DerivedBlog2 _root_query_DerivedBlog2 = new Root_Query_DerivedBlog2();
        
        /// Query for member DerivedBlog2
        public static Root_Query_DerivedBlog2 DerivedBlog2 {
            get {
                return _root_query_DerivedBlog2;
            }
        }
        
        /// Query for member Query_DerivedBlog2
        public partial class Query_DerivedBlog2<T1> : Query.QueryBuilder<T1>
         {
            
            /// Query for member .ctor
            public Query_DerivedBlog2(string name, string associationPath) : 
                    base(name, associationPath) {
            }
            
            /// Query for member .ctor
            public Query_DerivedBlog2(string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// Query for member 
            public virtual Query.PropertyQueryBuilder<T1> Name {
                get {
                    string temp = associationPath;
                    return new Query.PropertyQueryBuilder<T1>("Name", temp);
                }
            }
            
            /// Query for member 
            public virtual Query.PropertyQueryBuilder<T1> Attribute {
                get {
                    string temp = associationPath;
                    return new Query.PropertyQueryBuilder<T1>("Attribute", temp);
                }
            }
            
            /// Query for member 
            public virtual Query.QueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    return new Query.QueryBuilder<T1>("Id", temp);
                }
            }
            
            /// Query for member 
            public virtual Query_User<T1> Author {
                get {
                    string temp = associationPath;
                    temp = ((temp + ".") 
                                + "Author");
                    return new Query_User<T1>("Author", temp, true);
                }
            }
        }
        
        /// Query for member Root_Query_DerivedBlog2
        public partial class Root_Query_DerivedBlog2 : Query_DerivedBlog2<NHibernate.Query.Generator.Tests.ActiveRecord.DerivedBlog2> {
            
            /// Query for member .ctor
            public Root_Query_DerivedBlog2() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class OrderBy {
        
        /// Query for member DerivedBlog2
        public partial class DerivedBlog2 {
            
            /// Query for member Name
            public static Query.OrderByClause Name {
                get {
                    return new Query.OrderByClause("Name");
                }
            }
            
            /// Query for member Attribute
            public static Query.OrderByClause Attribute {
                get {
                    return new Query.OrderByClause("Attribute");
                }
            }
            
            /// Query for member Id
            public static Query.OrderByClause Id {
                get {
                    return new Query.OrderByClause("Id");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// Query for member DerivedBlog2
        public partial class DerivedBlog2 {
            
            /// Query for member Name
            public static Query.PropertyProjectionBuilder Name {
                get {
                    return new Query.PropertyProjectionBuilder("Name");
                }
            }
            
            /// Query for member Attribute
            public static Query.PropertyProjectionBuilder Attribute {
                get {
                    return new Query.PropertyProjectionBuilder("Attribute");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// Query for member DerivedBlog2
        public partial class DerivedBlog2 {
            
            /// Query for member Name
            public static NHibernate.Expression.IProjection Name {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Name");
                }
            }
            
            /// Query for member Attribute
            public static NHibernate.Expression.IProjection Attribute {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Attribute");
                }
            }
        }
    }
}
