//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        /// <summary>
        /// Query helper for member Where.DerivedBlog2
        /// </summary>
        public static Root_Query_DerivedBlog2 DerivedBlog2 {
            get {
                return new Root_Query_DerivedBlog2();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_DerivedBlog2
        /// </summary>
        public partial class Query_DerivedBlog2<T1> : QueryBuilder<T1>
         {
            
            /// <summary>
            /// Query helper for member Query_DerivedBlog2..ctor
            /// </summary>
            public Query_DerivedBlog2(QueryBuilder<T1> parent, string name, string associationPath) : 
                    base(parent, name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_DerivedBlog2..ctor
            /// </summary>
            public Query_DerivedBlog2(QueryBuilder<T1> parent, string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(parent, name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_DerivedBlog2.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Name {
                get {
                    string temp = associationPath;
                    return new PropertyQueryBuilder<T1>(this, "Name", temp);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_DerivedBlog2.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Attribute {
                get {
                    string temp = associationPath;
                    return new PropertyQueryBuilder<T1>(this, "Attribute", temp);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_DerivedBlog2.
            /// </summary>
            public virtual QueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    return new QueryBuilder<T1>(this, "Id", temp);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_DerivedBlog2.
            /// </summary>
            public virtual Query_User<T1> Author {
                get {
                    string temp = associationPath;
                    temp = ((temp + ".") 
                                + "Author");
                    return new Query_User<T1>(this, "Author", temp, true);
                }
            }
            
            public virtual Query_Collection_Posts Posts {
                get {
                    string temp = associationPath;
                    temp = (temp + ".Posts");
                    return new Query_Collection_Posts(this, "Posts", temp);
                }
            }
            
            public class Query_Collection_Posts : CollectionQueryBuilder<T1> {
                
                public Query_Collection_Posts(QueryBuilder<T1> parent, string name, string associationPath) : 
                        base(parent, name, associationPath) {
                }
                
                public virtual Query_Post<T1> With() {
                    Query_Post<T1> query = new Query_Post<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    return query;
                }
                
                public virtual Query_Post<T1> With(NHibernate.SqlCommand.JoinType joinType) {
                    Query_Post<T1> query = new Query_Post<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    return query;
                }
                
                public virtual Query_Post<T1> With(NHibernate.FetchMode fetchMode) {
                    Query_Post<T1> query = new Query_Post<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = fetchMode;
                    return query;
                }
                
                public virtual Query_Post<T1> With(NHibernate.SqlCommand.JoinType joinType, NHibernate.FetchMode fetchMode) {
                    Query_Post<T1> query = new Query_Post<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = fetchMode;
                    return query;
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_DerivedBlog2
        /// </summary>
        public partial class Root_Query_DerivedBlog2 : Query_DerivedBlog2<NHibernate.Query.Generator.Tests.ActiveRecord.DerivedBlog2> {
            
            /// <summary>
            /// Query helper for member Root_Query_DerivedBlog2..ctor
            /// </summary>
            public Root_Query_DerivedBlog2() : 
                    base(null, "this", null) {
            }
        }
    }
    
    public partial class OrderBy {
        
        /// <summary>
        /// Query helper for member OrderBy.DerivedBlog2
        /// </summary>
        public partial class DerivedBlog2 {
            
            /// <summary>
            /// Query helper for member DerivedBlog2.Name
            /// </summary>
            public static OrderByClause Name {
                get {
                    return new OrderByClause("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member DerivedBlog2.Attribute
            /// </summary>
            public static OrderByClause Attribute {
                get {
                    return new OrderByClause("Attribute");
                }
            }
            
            /// <summary>
            /// Query helper for member DerivedBlog2.Id
            /// </summary>
            public static OrderByClause Id {
                get {
                    return new OrderByClause("Id");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// <summary>
        /// Query helper for member ProjectBy.DerivedBlog2
        /// </summary>
        public partial class DerivedBlog2 {
            
            /// <summary>
            /// Query helper for member DerivedBlog2.Name
            /// </summary>
            public static PropertyProjectionBuilder Name {
                get {
                    return new PropertyProjectionBuilder("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member DerivedBlog2.Attribute
            /// </summary>
            public static PropertyProjectionBuilder Attribute {
                get {
                    return new PropertyProjectionBuilder("Attribute");
                }
            }
            
            /// <summary>
            /// Query helper for member DerivedBlog2.Id
            /// </summary>
            public static NumericPropertyProjectionBuilder Id {
                get {
                    return new NumericPropertyProjectionBuilder("Id");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// <summary>
        /// Query helper for member GroupBy.DerivedBlog2
        /// </summary>
        public partial class DerivedBlog2 {
            
            /// <summary>
            /// Query helper for member DerivedBlog2.Name
            /// </summary>
            public static NHibernate.Expression.IProjection Name {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member DerivedBlog2.Attribute
            /// </summary>
            public static NHibernate.Expression.IProjection Attribute {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Attribute");
                }
            }
        }
    }
}
