//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        /// <summary>
        /// Query helper for member Where.Post
        /// </summary>
        public static Root_Query_Post Post {
            get {
                return new Root_Query_Post();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_Post
        /// </summary>
        public partial class Query_Post<T1> : QueryBuilder<T1>
         {
            
            /// <summary>
            /// Query helper for member Query_Post..ctor
            /// </summary>
            public Query_Post(string name, string associationPath) : 
                    base(name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_Post..ctor
            /// </summary>
            public Query_Post(string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_Post.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Title {
                get {
                    string temp = associationPath;
                    return new PropertyQueryBuilder<T1>("Title", temp);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_Post.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Contnet {
                get {
                    string temp = associationPath;
                    return new PropertyQueryBuilder<T1>("Contnet", temp);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_Post.
            /// </summary>
            public virtual QueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    return new QueryBuilder<T1>("Id", temp);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_Post.
            /// </summary>
            public virtual Query_Blog<T1> Blog {
                get {
                    string temp = associationPath;
                    temp = ((temp + ".") 
                                + "Blog");
                    return new Query_Blog<T1>("Blog", temp, true);
                }
            }
            
            public virtual CollectionQueryBuilder<T1> Comments {
                get {
                    string temp = associationPath;
                    return new CollectionQueryBuilder<T1>("Comments", temp);
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_Post
        /// </summary>
        public partial class Root_Query_Post : Query_Post<NHibernate.Query.Generator.Tests.ActiveRecord.Post> {
            
            /// <summary>
            /// Query helper for member Root_Query_Post..ctor
            /// </summary>
            public Root_Query_Post() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class OrderBy {
        
        /// <summary>
        /// Query helper for member OrderBy.Post
        /// </summary>
        public partial class Post {
            
            /// <summary>
            /// Query helper for member Post.Title
            /// </summary>
            public static OrderByClause Title {
                get {
                    return new OrderByClause("Title");
                }
            }
            
            /// <summary>
            /// Query helper for member Post.Contnet
            /// </summary>
            public static OrderByClause Contnet {
                get {
                    return new OrderByClause("Contnet");
                }
            }
            
            /// <summary>
            /// Query helper for member Post.Id
            /// </summary>
            public static OrderByClause Id {
                get {
                    return new OrderByClause("Id");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// <summary>
        /// Query helper for member ProjectBy.Post
        /// </summary>
        public partial class Post {
            
            /// <summary>
            /// Query helper for member Post.Title
            /// </summary>
            public static PropertyProjectionBuilder Title {
                get {
                    return new PropertyProjectionBuilder("Title");
                }
            }
            
            /// <summary>
            /// Query helper for member Post.Contnet
            /// </summary>
            public static PropertyProjectionBuilder Contnet {
                get {
                    return new PropertyProjectionBuilder("Contnet");
                }
            }
            
            /// <summary>
            /// Query helper for member Post.Id
            /// </summary>
            public static NumericPropertyProjectionBuilder Id {
                get {
                    return new NumericPropertyProjectionBuilder("Id");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// <summary>
        /// Query helper for member GroupBy.Post
        /// </summary>
        public partial class Post {
            
            /// <summary>
            /// Query helper for member Post.Title
            /// </summary>
            public static NHibernate.Expression.IProjection Title {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Title");
                }
            }
            
            /// <summary>
            /// Query helper for member Post.Contnet
            /// </summary>
            public static NHibernate.Expression.IProjection Contnet {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Contnet");
                }
            }
        }
    }
}
