//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        /// <summary>
        /// Query helper for member Where.WeirdClass
        /// </summary>
        public static Root_Query_WeirdClass WeirdClass {
            get {
                return new Root_Query_WeirdClass();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_WeirdClass
        /// </summary>
        public partial class Query_WeirdClass<T1> : Query.QueryBuilder<T1>
         {
            
            /// <summary>
            /// Query helper for member Query_WeirdClass..ctor
            /// </summary>
            public Query_WeirdClass(string name, string associationPath) : 
                    base(name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_WeirdClass..ctor
            /// </summary>
            public Query_WeirdClass(string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_WeirdClass.Address
            /// </summary>
            public virtual Query_Address<T1> Address {
                get {
                    return new Query_Address<T1>("Address", null);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_WeirdClass.Key
            /// </summary>
            public virtual Query_Key<T1> Key {
                get {
                    return new Query_Key<T1>("Key", associationPath);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_WeirdClass.Query_Address
            /// </summary>
            public partial class Query_Address<T2> : Query.QueryBuilder<T2>
             {
                
                /// <summary>
                /// Query helper for member Query_Address..ctor
                /// </summary>
                public Query_Address(string name, string associationPath) : 
                        base(name, associationPath) {
                }
                
                /// <summary>
                /// Query helper for member Query_Address..ctor
                /// </summary>
                public Query_Address(string name, string associationPath, bool backTrackAssociationOnEquality) : 
                        base(name, associationPath, backTrackAssociationOnEquality) {
                }
                
                /// <summary>
                /// Query helper for member Query_Address.
                /// </summary>
                public virtual Query.PropertyQueryBuilder<T1> Street {
                    get {
                        string temp = associationPath;
                        return new Query.PropertyQueryBuilder<T1>("Address.Street", temp);
                    }
                }
                
                /// <summary>
                /// Query helper for member Query_Address.Electronic
                /// </summary>
                public virtual Query_Electronic<T1> Electronic {
                    get {
                        return new Query_Electronic<T1>("Address.Electronic", null);
                    }
                }
                
                /// <summary>
                /// Query helper for member Query_Address.Query_Electronic
                /// </summary>
                public partial class Query_Electronic<T3> : Query.QueryBuilder<T3>
                 {
                    
                    /// <summary>
                    /// Query helper for member Query_Electronic..ctor
                    /// </summary>
                    public Query_Electronic(string name, string associationPath) : 
                            base(name, associationPath) {
                    }
                    
                    /// <summary>
                    /// Query helper for member Query_Electronic..ctor
                    /// </summary>
                    public Query_Electronic(string name, string associationPath, bool backTrackAssociationOnEquality) : 
                            base(name, associationPath, backTrackAssociationOnEquality) {
                    }
                    
                    /// <summary>
                    /// Query helper for member Query_Electronic.
                    /// </summary>
                    public virtual Query.PropertyQueryBuilder<T1> Email {
                        get {
                            string temp = associationPath;
                            return new Query.PropertyQueryBuilder<T1>("Address.Electronic.Email", temp);
                        }
                    }
                }
            }
            
            /// <summary>
            /// Query helper for member Query_WeirdClass.Query_Key
            /// </summary>
            public partial class Query_Key<T4> : Query.QueryBuilder<T4>
             {
                
                /// <summary>
                /// Query helper for member Query_Key..ctor
                /// </summary>
                public Query_Key(string name, string associationPath) : 
                        base(name, associationPath) {
                }
                
                /// <summary>
                /// Query helper for member Query_Key..ctor
                /// </summary>
                public Query_Key(string name, string associationPath, bool backTrackAssociationOnEquality) : 
                        base(name, associationPath, backTrackAssociationOnEquality) {
                }
                
                /// <summary>
                /// Query helper for member Query_Key.
                /// </summary>
                public virtual Query.PropertyQueryBuilder<T1> Department {
                    get {
                        string temp = associationPath;
                        return new Query.PropertyQueryBuilder<T1>("Key.Department", temp);
                    }
                }
                
                /// <summary>
                /// Query helper for member Query_Key.
                /// </summary>
                public virtual Query.PropertyQueryBuilder<T1> Level {
                    get {
                        string temp = associationPath;
                        return new Query.PropertyQueryBuilder<T1>("Key.Level", temp);
                    }
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_WeirdClass
        /// </summary>
        public partial class Root_Query_WeirdClass : Query_WeirdClass<NHibernate.Query.Generator.Tests.ActiveRecord.WeirdClass> {
            
            /// <summary>
            /// Query helper for member Root_Query_WeirdClass..ctor
            /// </summary>
            public Root_Query_WeirdClass() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class OrderBy {
        
        /// <summary>
        /// Query helper for member OrderBy.WeirdClass
        /// </summary>
        public partial class WeirdClass {
            
            /// <summary>
            /// Query helper for member WeirdClass.Address
            /// </summary>
            public partial class Address {
                
                /// <summary>
                /// Query helper for member Address.Street
                /// </summary>
                public static Query.OrderByClause Street {
                    get {
                        return new Query.OrderByClause("Address.Street");
                    }
                }
                
                /// <summary>
                /// Query helper for member Address.Electronic
                /// </summary>
                public partial class Electronic {
                    
                    /// <summary>
                    /// Query helper for member Electronic.Email
                    /// </summary>
                    public static Query.OrderByClause Email {
                        get {
                            return new Query.OrderByClause("Address.Electronic.Email");
                        }
                    }
                }
            }
            
            /// <summary>
            /// Query helper for member WeirdClass.Key
            /// </summary>
            public partial class Key {
                
                /// <summary>
                /// Query helper for member Key.Department
                /// </summary>
                public static Query.OrderByClause Department {
                    get {
                        return new Query.OrderByClause("Key.Department");
                    }
                }
                
                /// <summary>
                /// Query helper for member Key.Level
                /// </summary>
                public static Query.OrderByClause Level {
                    get {
                        return new Query.OrderByClause("Key.Level");
                    }
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// <summary>
        /// Query helper for member ProjectBy.WeirdClass
        /// </summary>
        public partial class WeirdClass {
            
            /// <summary>
            /// Query helper for member WeirdClass.Address
            /// </summary>
            public partial class Address {
                
                /// <summary>
                /// Query helper for member Address.Street
                /// </summary>
                public static Query.PropertyProjectionBuilder Street {
                    get {
                        return new Query.PropertyProjectionBuilder("Address.Street");
                    }
                }
                
                /// <summary>
                /// Query helper for member Address.Electronic
                /// </summary>
                public partial class Electronic {
                    
                    /// <summary>
                    /// Query helper for member Electronic.Email
                    /// </summary>
                    public static Query.PropertyProjectionBuilder Email {
                        get {
                            return new Query.PropertyProjectionBuilder("Address.Electronic.Email");
                        }
                    }
                }
            }
            
            /// <summary>
            /// Query helper for member WeirdClass.Key
            /// </summary>
            public partial class Key {
                
                /// <summary>
                /// Query helper for member Key.Department
                /// </summary>
                public static Query.PropertyProjectionBuilder Department {
                    get {
                        return new Query.PropertyProjectionBuilder("Key.Department");
                    }
                }
                
                /// <summary>
                /// Query helper for member Key.Level
                /// </summary>
                public static Query.NumericPropertyProjectionBuilder Level {
                    get {
                        return new Query.NumericPropertyProjectionBuilder("Key.Level");
                    }
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// <summary>
        /// Query helper for member GroupBy.WeirdClass
        /// </summary>
        public partial class WeirdClass {
            
            /// <summary>
            /// Query helper for member WeirdClass.Address
            /// </summary>
            public partial class Address {
                
                /// <summary>
                /// Query helper for member Address.Street
                /// </summary>
                public static NHibernate.Expression.IProjection Street {
                    get {
                        return NHibernate.Expression.Projections.GroupProperty("Address.Street");
                    }
                }
                
                /// <summary>
                /// Query helper for member Address.Electronic
                /// </summary>
                public partial class Electronic {
                    
                    /// <summary>
                    /// Query helper for member Electronic.Email
                    /// </summary>
                    public static NHibernate.Expression.IProjection Email {
                        get {
                            return NHibernate.Expression.Projections.GroupProperty("Address.Electronic.Email");
                        }
                    }
                }
            }
            
            /// <summary>
            /// Query helper for member WeirdClass.Key
            /// </summary>
            public partial class Key {
                
                /// <summary>
                /// Query helper for member Key.Department
                /// </summary>
                public static NHibernate.Expression.IProjection Department {
                    get {
                        return NHibernate.Expression.Projections.GroupProperty("Key.Department");
                    }
                }
                
                /// <summary>
                /// Query helper for member Key.Level
                /// </summary>
                public static NHibernate.Expression.IProjection Level {
                    get {
                        return NHibernate.Expression.Projections.GroupProperty("Key.Level");
                    }
                }
            }
        }
    }
}
