//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        /// Query for member _root_query_Componnet
        static Root_Query_Componnet _root_query_Componnet = new Root_Query_Componnet();
        
        /// Query for member Componnet
        public static Root_Query_Componnet Componnet {
            get {
                return _root_query_Componnet;
            }
        }
        
        /// Query for member Query_Componnet
        public partial class Query_Componnet<T1> : Query.QueryBuilder<T1>
         {
            
            /// Query for member .ctor
            public Query_Componnet(string name, string associationPath) : 
                    base(name, associationPath) {
            }
            
            /// Query for member .ctor
            public Query_Componnet(string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// Query for member 
            public virtual Query.PropertyQueryBuilder<T1> Version {
                get {
                    string temp = associationPath;
                    return new Query.PropertyQueryBuilder<T1>("Version", temp);
                }
            }
            
            /// Query for member 
            public virtual Query.QueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    return new Query.QueryBuilder<T1>("Id", temp);
                }
            }
        }
        
        /// Query for member Root_Query_Componnet
        public partial class Root_Query_Componnet : Query_Componnet<NHibernate.Query.Generator.Tests.ActiveRecord.Componnet> {
            
            /// Query for member .ctor
            public Root_Query_Componnet() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class OrderBy {
        
        /// Query for member Componnet
        public partial class Componnet {
            
            /// Query for member Version
            public static Query.OrderByClause Version {
                get {
                    return new Query.OrderByClause("Version");
                }
            }
            
            /// Query for member Id
            public static Query.OrderByClause Id {
                get {
                    return new Query.OrderByClause("Id");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// Query for member Componnet
        public partial class Componnet {
            
            /// Query for member Version
            public static Query.PropertyProjectionBuilder Version {
                get {
                    return new Query.PropertyProjectionBuilder("Version");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// Query for member Componnet
        public partial class Componnet {
            
            /// Query for member Version
            public static NHibernate.Expression.IProjection Version {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Version");
                }
            }
        }
    }
}
