//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class For {
        
        /// Query Builder for member Post
        public static Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Post> Post {
            get {
                return new Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Post>();
            }
        }
    }
    
    public partial class Where {
        
        /// Where for member _root_Where_Post
        static Root_Where_Post _root_Where_Post = new Root_Where_Post();
        
        /// Where for member Post
        public static Root_Where_Post Post {
            get {
                return _root_Where_Post;
            }
        }
        
        /// Where for member Where_Post
        public partial class Where_Post<T1> : Query.WhereClause<T1>
         {
            
            /// Where for member .ctor
            public Where_Post(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// Where for member .ctor
            public Where_Post(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// Where for member 
            public virtual Query.WhereClauseProperty<T1> Title {
                get {
                    string temp = QpAssociationPath;
                    return new Query.WhereClauseProperty<T1>("Title", temp);
                }
            }
            
            /// Where for member 
            public virtual Query.WhereClauseProperty<T1> Contnet {
                get {
                    string temp = QpAssociationPath;
                    return new Query.WhereClauseProperty<T1>("Contnet", temp);
                }
            }
            
            /// Where for member 
            public virtual Query.WhereClause<T1> Id {
                get {
                    string temp = QpAssociationPath;
                    return new Query.WhereClause<T1>("Id", temp);
                }
            }
            
            /// Where for member 
            public virtual Where_Blog<T1> Blog {
                get {
                    string temp = QpAssociationPath;
                    temp = ((temp + ".") 
                                + "Blog");
                    return new Where_Blog<T1>("Blog", temp, true);
                }
            }
        }
        
        /// Where for member Root_Where_Post
        public partial class Root_Where_Post : Where_Post<NHibernate.Query.Generator.Tests.ActiveRecord.Post> {
            
            /// Where for member .ctor
            public Root_Where_Post() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// Projection for member _root_Projection_Post
        static Root_Projection_Post _root_Projection_Post = new Root_Projection_Post();
        
        /// Projection for member Post
        public static Root_Projection_Post Post {
            get {
                return _root_Projection_Post;
            }
        }
        
        /// Projection for member Projection_Post
        public partial class Projection_Post<T2> : Query.ProjectionEntity<T2>
         {
            
            /// Projection for member .ctor
            public Projection_Post(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// Projection for member .ctor
            public Projection_Post(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// Projection for member 
            public virtual Query.ProjectionClauseProperty<T2> Title {
                get {
                    string temp = QpAssociationPath;
                    return new Query.ProjectionClauseProperty<T2>("Title", temp);
                }
            }
            
            /// Projection for member 
            public virtual Query.ProjectionClauseProperty<T2> Contnet {
                get {
                    string temp = QpAssociationPath;
                    return new Query.ProjectionClauseProperty<T2>("Contnet", temp);
                }
            }
            
            /// Projection for member 
            public virtual Query.ProjectionClausePropertyNumeric<T2> Id {
                get {
                    string temp = QpAssociationPath;
                    return new Query.ProjectionClausePropertyNumeric<T2>("Id", temp);
                }
            }
            
            /// Projection for member 
            public virtual Projection_Blog<T2> Blog {
                get {
                    string temp = QpAssociationPath;
                    temp = ((temp + ".") 
                                + "Blog");
                    return new Projection_Blog<T2>("Blog", temp, true);
                }
            }
        }
        
        /// Projection for member Root_Projection_Post
        public partial class Root_Projection_Post : Projection_Post<NHibernate.Query.Generator.Tests.ActiveRecord.Post> {
            
            /// Projection for member .ctor
            public Root_Projection_Post() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class OrderBy {
        
        /// OrderBy for member _root_OrderBy_Post
        static Root_OrderBy_Post _root_OrderBy_Post = new Root_OrderBy_Post();
        
        /// OrderBy for member Post
        public static Root_OrderBy_Post Post {
            get {
                return _root_OrderBy_Post;
            }
        }
        
        /// OrderBy for member OrderBy_Post
        public partial class OrderBy_Post<T3> : Query.QueryPart
         {
            
            /// OrderBy for member .ctor
            public OrderBy_Post(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// OrderBy for member .ctor
            public OrderBy_Post(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// OrderBy for member 
            public virtual Query.OrderByClauseProperty<T3> Title {
                get {
                    string temp = QpAssociationPath;
                    return new Query.OrderByClauseProperty<T3>("Title", temp);
                }
            }
            
            /// OrderBy for member 
            public virtual Query.OrderByClauseProperty<T3> Contnet {
                get {
                    string temp = QpAssociationPath;
                    return new Query.OrderByClauseProperty<T3>("Contnet", temp);
                }
            }
            
            /// OrderBy for member 
            public virtual Query.OrderByClauseProperty<T3> Id {
                get {
                    string temp = QpAssociationPath;
                    return new Query.OrderByClauseProperty<T3>("Id", temp);
                }
            }
            
            /// OrderBy for member 
            public virtual OrderBy_Blog<T3> Blog {
                get {
                    string temp = QpAssociationPath;
                    temp = ((temp + ".") 
                                + "Blog");
                    return new OrderBy_Blog<T3>("Blog", temp, true);
                }
            }
        }
        
        /// OrderBy for member Root_OrderBy_Post
        public partial class Root_OrderBy_Post : OrderBy_Post<NHibernate.Query.Generator.Tests.ActiveRecord.Post> {
            
            /// OrderBy for member .ctor
            public Root_OrderBy_Post() : 
                    base("this", null) {
            }
        }
    }
}
