//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class For {
        
        /// Query Builder for member Blog
        public static Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Blog> Blog {
            get {
                return new Query.QueryBuilder<NHibernate.Query.Generator.Tests.ActiveRecord.Blog>();
            }
        }
    }
    
    public partial class Where {
        
        /// Where for member _root_Where_Blog
        static Root_Where_Blog _root_Where_Blog = new Root_Where_Blog();
        
        /// Where for member Blog
        public static Root_Where_Blog Blog {
            get {
                return _root_Where_Blog;
            }
        }
        
        /// Where for member Where_Blog
        public partial class Where_Blog<T1> : Query.WhereClause<T1>
         {
            
            /// Where for member .ctor
            public Where_Blog(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// Where for member .ctor
            public Where_Blog(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// Where for member 
            public virtual Query.WhereClauseProperty<T1> Name {
                get {
                    string temp = QpAssociationPath;
                    return new Query.WhereClauseProperty<T1>("Name", temp);
                }
            }
            
            /// Where for member 
            public virtual Query.WhereClause<T1> Id {
                get {
                    string temp = QpAssociationPath;
                    return new Query.WhereClause<T1>("Id", temp);
                }
            }
            
            /// Where for member 
            public virtual Where_User<T1> Author {
                get {
                    string temp = QpAssociationPath;
                    temp = ((temp + ".") 
                                + "Author");
                    return new Where_User<T1>("Author", temp, true);
                }
            }
        }
        
        /// Where for member Root_Where_Blog
        public partial class Root_Where_Blog : Where_Blog<NHibernate.Query.Generator.Tests.ActiveRecord.Blog> {
            
            /// Where for member .ctor
            public Root_Where_Blog() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// Projection for member _root_Projection_Blog
        static Root_Projection_Blog _root_Projection_Blog = new Root_Projection_Blog();
        
        /// Projection for member Blog
        public static Root_Projection_Blog Blog {
            get {
                return _root_Projection_Blog;
            }
        }
        
        /// Projection for member Projection_Blog
        public partial class Projection_Blog<T2> : Query.ProjectionEntity<T2>
         {
            
            /// Projection for member .ctor
            public Projection_Blog(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// Projection for member .ctor
            public Projection_Blog(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// Projection for member 
            public virtual Query.ProjectionClauseProperty<T2> Name {
                get {
                    string temp = QpAssociationPath;
                    return new Query.ProjectionClauseProperty<T2>("Name", temp);
                }
            }
            
            /// Projection for member 
            public virtual Query.ProjectionClauseProperty<T2> Id {
                get {
                    string temp = QpAssociationPath;
                    return new Query.ProjectionClauseProperty<T2>("Id", temp);
                }
            }
            
            /// Projection for member 
            public virtual Projection_User<T2> Author {
                get {
                    string temp = QpAssociationPath;
                    temp = ((temp + ".") 
                                + "Author");
                    return new Projection_User<T2>("Author", temp, true);
                }
            }
        }
        
        /// Projection for member Root_Projection_Blog
        public partial class Root_Projection_Blog : Projection_Blog<NHibernate.Query.Generator.Tests.ActiveRecord.Blog> {
            
            /// Projection for member .ctor
            public Root_Projection_Blog() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class OrderBy {
        
        /// OrderBy for member _root_OrderBy_Blog
        static Root_OrderBy_Blog _root_OrderBy_Blog = new Root_OrderBy_Blog();
        
        /// OrderBy for member Blog
        public static Root_OrderBy_Blog Blog {
            get {
                return _root_OrderBy_Blog;
            }
        }
        
        /// OrderBy for member OrderBy_Blog
        public partial class OrderBy_Blog<T3> : Query.QueryPart
         {
            
            /// OrderBy for member .ctor
            public OrderBy_Blog(string QpName, string QpAssociationPath) : 
                    base(QpName, QpAssociationPath) {
            }
            
            /// OrderBy for member .ctor
            public OrderBy_Blog(string QpName, string QpAssociationPath, bool QpBackTrack) : 
                    base(QpName, QpAssociationPath, QpBackTrack) {
            }
            
            /// OrderBy for member 
            public virtual Query.OrderByClauseProperty<T3> Name {
                get {
                    string temp = QpAssociationPath;
                    return new Query.OrderByClauseProperty<T3>("Name", temp);
                }
            }
            
            /// OrderBy for member 
            public virtual Query.OrderByClauseProperty<T3> Id {
                get {
                    string temp = QpAssociationPath;
                    return new Query.OrderByClauseProperty<T3>("Id", temp);
                }
            }
            
            /// OrderBy for member 
            public virtual OrderBy_User<T3> Author {
                get {
                    string temp = QpAssociationPath;
                    temp = ((temp + ".") 
                                + "Author");
                    return new OrderBy_User<T3>("Author", temp, true);
                }
            }
        }
        
        /// OrderBy for member Root_OrderBy_Blog
        public partial class Root_OrderBy_Blog : OrderBy_Blog<NHibernate.Query.Generator.Tests.ActiveRecord.Blog> {
            
            /// OrderBy for member .ctor
            public Root_OrderBy_Blog() : 
                    base("this", null) {
            }
        }
    }
}
