//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        /// <summary>
        /// Query helper for member Where.Application
        /// </summary>
        public static Root_Query_Application Application {
            get {
                return new Root_Query_Application();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_Application
        /// </summary>
        public partial class Query_Application<T1> : QueryBuilder<T1>
         {
            
            /// <summary>
            /// Query helper for member Query_Application..ctor
            /// </summary>
            public Query_Application(QueryBuilder<T1> parent, string name, string associationPath) : 
                    base(parent, name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_Application..ctor
            /// </summary>
            public Query_Application(QueryBuilder<T1> parent, string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(parent, name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_Application.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Name {
                get {
                    string temp = associationPath;
                    return new PropertyQueryBuilder<T1>(this, "Name", temp);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_Application.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Description {
                get {
                    string temp = associationPath;
                    return new PropertyQueryBuilder<T1>(this, "Description", temp);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_Application.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Obsolete {
                get {
                    string temp = associationPath;
                    return new PropertyQueryBuilder<T1>(this, "Obsolete", temp);
                }
            }
            
            /// <summary>
            /// Query helper for member Query_Application.
            /// </summary>
            public virtual QueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    return new QueryBuilder<T1>(this, "Id", temp);
                }
            }
            
            public virtual Query_Collection_Operations Operations {
                get {
                    string temp = associationPath;
                    temp = (temp + ".Operations");
                    return new Query_Collection_Operations(this, "Operations", temp);
                }
            }
            
            public class Query_Collection_Operations : CollectionQueryBuilder<T1> {
                
                public Query_Collection_Operations(QueryBuilder<T1> parent, string name, string associationPath) : 
                        base(parent, name, associationPath) {
                }
                
                public virtual Query_Operation<T1> With() {
                    Query_Operation<T1> query = new Query_Operation<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    return query;
                }
                
                public virtual Query_Operation<T1> With(NHibernate.SqlCommand.JoinType joinType) {
                    Query_Operation<T1> query = new Query_Operation<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    return query;
                }
                
                public virtual Query_Operation<T1> With(NHibernate.FetchMode fetchMode) {
                    Query_Operation<T1> query = new Query_Operation<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = fetchMode;
                    return query;
                }
                
                public virtual Query_Operation<T1> With(NHibernate.SqlCommand.JoinType joinType, NHibernate.FetchMode fetchMode) {
                    Query_Operation<T1> query = new Query_Operation<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = fetchMode;
                    return query;
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_Application
        /// </summary>
        public partial class Root_Query_Application : Query_Application<NHibernate.Query.Generator.Tests.WithEagerFetch.Application> {
            
            /// <summary>
            /// Query helper for member Root_Query_Application..ctor
            /// </summary>
            public Root_Query_Application() : 
                    base(null, "this", null) {
            }
        }
    }
    
    public partial class OrderBy {
        
        /// <summary>
        /// Query helper for member OrderBy.Application
        /// </summary>
        public partial class Application {
            
            /// <summary>
            /// Query helper for member Application.Name
            /// </summary>
            public static OrderByClause Name {
                get {
                    return new OrderByClause("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member Application.Description
            /// </summary>
            public static OrderByClause Description {
                get {
                    return new OrderByClause("Description");
                }
            }
            
            /// <summary>
            /// Query helper for member Application.Obsolete
            /// </summary>
            public static OrderByClause Obsolete {
                get {
                    return new OrderByClause("Obsolete");
                }
            }
            
            /// <summary>
            /// Query helper for member Application.Id
            /// </summary>
            public static OrderByClause Id {
                get {
                    return new OrderByClause("Id");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// <summary>
        /// Query helper for member ProjectBy.Application
        /// </summary>
        public partial class Application {
            
            /// <summary>
            /// Query helper for member Application.Name
            /// </summary>
            public static PropertyProjectionBuilder Name {
                get {
                    return new PropertyProjectionBuilder("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member Application.Description
            /// </summary>
            public static PropertyProjectionBuilder Description {
                get {
                    return new PropertyProjectionBuilder("Description");
                }
            }
            
            /// <summary>
            /// Query helper for member Application.Obsolete
            /// </summary>
            public static PropertyProjectionBuilder Obsolete {
                get {
                    return new PropertyProjectionBuilder("Obsolete");
                }
            }
            
            /// <summary>
            /// Query helper for member Application.Id
            /// </summary>
            public static PropertyProjectionBuilder Id {
                get {
                    return new PropertyProjectionBuilder("Id");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// <summary>
        /// Query helper for member GroupBy.Application
        /// </summary>
        public partial class Application {
            
            /// <summary>
            /// Query helper for member Application.Name
            /// </summary>
            public static NHibernate.Expression.IProjection Name {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member Application.Description
            /// </summary>
            public static NHibernate.Expression.IProjection Description {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Description");
                }
            }
            
            /// <summary>
            /// Query helper for member Application.Obsolete
            /// </summary>
            public static NHibernate.Expression.IProjection Obsolete {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Obsolete");
                }
            }
        }
    }
}
