//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Rhino")]
[assembly: AssemblyCopyright("Oren Eini (c) 2006")]
[assembly: AssemblyDescription("Rhino.Generators")]
[assembly: AssemblyInformationalVersion("1.0.457")]
[assembly: AssemblyTitle("Rhino.Generators")]
[assembly: AssemblyVersion("1.0.457")]


