//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query {
    
    
    public partial class Where {
        
        static Root_Query_Post _root_query_Post = new Root_Query_Post();
        
        public static Root_Query_Post Post {
            get {
                return _root_query_Post;
            }
        }
        
        public partial class Query_Post<T1> : Query.QueryBuilder<T1>
         {
            
            public Query_Post(string name, string assoicationPath) : 
                    base(name, assoicationPath) {
            }
            
            public Query_Post(string name, string assoicationPath, bool backTrackAssoicationOnEquality) : 
                    base(name, assoicationPath, backTrackAssoicationOnEquality) {
            }
            
            public virtual Query.PropertyQueryBuilder<T1> Content {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<T1>("Content", temp);
                }
            }
            
            public virtual Query.PropertyQueryBuilder<T1> Created {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<T1>("Created", temp);
                }
            }
            
            public virtual Query.PropertyQueryBuilder<T1> Modified {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<T1>("Modified", temp);
                }
            }
            
            public virtual Query.PropertyQueryBuilder<T1> Title {
                get {
                    string temp = assoicationPath;
                    return new Query.PropertyQueryBuilder<T1>("Title", temp);
                }
            }
            
            public virtual Query.QueryBuilder<T1> PostId {
                get {
                    string temp = assoicationPath;
                    return new Query.QueryBuilder<T1>("PostId", temp);
                }
            }
        }
        
        public partial class Root_Query_Post : Query_Post<Model.Post> {
            
            public Root_Query_Post() : 
                    base("this", null) {
            }
        }
    }
    
    public partial class OrderBy {
        
        public partial class Post {
            
            public static Query.OrderByClause Content {
                get {
                    return new Query.OrderByClause("Content");
                }
            }
            
            public static Query.OrderByClause Created {
                get {
                    return new Query.OrderByClause("Created");
                }
            }
            
            public static Query.OrderByClause Modified {
                get {
                    return new Query.OrderByClause("Modified");
                }
            }
            
            public static Query.OrderByClause Title {
                get {
                    return new Query.OrderByClause("Title");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        public partial class Post {
            
            public static Query.PropertyProjectionBuilder Content {
                get {
                    return new Query.PropertyProjectionBuilder("Content");
                }
            }
            
            public static Query.PropertyProjectionBuilder Created {
                get {
                    return new Query.PropertyProjectionBuilder("Created");
                }
            }
            
            public static Query.PropertyProjectionBuilder Modified {
                get {
                    return new Query.PropertyProjectionBuilder("Modified");
                }
            }
            
            public static Query.PropertyProjectionBuilder Title {
                get {
                    return new Query.PropertyProjectionBuilder("Title");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        public partial class Post {
            
            public static NHibernate.Expression.IProjection Content {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Content");
                }
            }
            
            public static NHibernate.Expression.IProjection Created {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Created");
                }
            }
            
            public static NHibernate.Expression.IProjection Modified {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Modified");
                }
            }
            
            public static NHibernate.Expression.IProjection Title {
                get {
                    return NHibernate.Expression.Projections.GroupProperty("Title");
                }
            }
        }
    }
}
