using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("NHibernate.Query.Generator.Model for Microsoft .NET Framework 3.5")]
[assembly: AssemblyDescriptionAttribute("NHibernate Query Generator - Generate strongly typed queries for NHibernate")]
[assembly: AssemblyCompanyAttribute("Rhino Tools Project")]
[assembly: AssemblyProductAttribute("NHibernate.Query.Generator.Model")]
[assembly: AssemblyCopyrightAttribute("Rhino Tools Project, original author or authors")]
[assembly: AssemblyVersionAttribute("2.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0.1231")]
[assembly: AssemblyFileVersionAttribute("2.0.0.1231")]
[assembly: AssemblyDelaySignAttribute(false)]

#if MONO
[assembly: AssemblyKeyFileAttribute(@"c:\Home\Develop\RhinoTools-Nant\ayende-open-source.snk")]
#endif
