//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 20/12/2007 1:53:02 PM
// This source code was auto-generated by NHQG (), Version 1.9.1.0.
// 
namespace Query {
    
    
    public partial class Where {
        
        /// <summary>
        /// Query helper for member Where.CompositeIdParent
        /// </summary>
        public static Root_Query_CompositeIdParent CompositeIdParent {
            get {
                return new Root_Query_CompositeIdParent();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_CompositeIdParent
        /// </summary>
        public partial class Query_CompositeIdParent<T1> : QueryBuilder<T1>
         {
            
            /// <summary>
            /// Query helper for member Query_CompositeIdParent..ctor
            /// </summary>
            public Query_CompositeIdParent() : 
                    this(null, "this", null) {
            }
            
            /// <summary>
            /// Query helper for member Query_CompositeIdParent..ctor
            /// </summary>
            public Query_CompositeIdParent(QueryBuilder<T1> parent, string name, string associationPath) : 
                    base(parent, name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_CompositeIdParent..ctor
            /// </summary>
            public Query_CompositeIdParent(QueryBuilder<T1> parent, string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(parent, name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_CompositeIdParent.
            /// </summary>
            public virtual IdQueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    IdQueryBuilder<T1> child = new IdQueryBuilder<T1>(null, "Id", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            public virtual Query_Collection_Children Children {
                get {
                    string temp = associationPath;
                    temp = (temp + ".Children");
                    return new Query_Collection_Children(this, "Children", temp);
                }
            }
            
            public class Query_Collection_Children : CollectionQueryBuilder<T1> {
                
                public Query_Collection_Children(QueryBuilder<T1> parent, string name, string associationPath) : 
                        base(parent, name, associationPath) {
                }
                
                public virtual Query_CompositeIdChild<T1> With() {
                    Query_CompositeIdChild<T1> query = new Query_CompositeIdChild<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_CompositeIdChild<T1> With(NHibernate.SqlCommand.JoinType joinType) {
                    Query_CompositeIdChild<T1> query = new Query_CompositeIdChild<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_CompositeIdChild<T1> With(NHibernate.FetchMode fetchMode) {
                    Query_CompositeIdChild<T1> query = new Query_CompositeIdChild<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = fetchMode;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_CompositeIdChild<T1> With(NHibernate.SqlCommand.JoinType joinType, NHibernate.FetchMode fetchMode) {
                    Query_CompositeIdChild<T1> query = new Query_CompositeIdChild<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = fetchMode;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_CompositeIdParent
        /// </summary>
        public partial class Root_Query_CompositeIdParent : Query_CompositeIdParent<NHibernate.Query.Generator.Tests.CompositeIds.CompositeIdParent> {
        }
    }
    
    public partial class OrderBy {
        
        /// <summary>
        /// Query helper for member OrderBy.CompositeIdParent
        /// </summary>
        public partial class CompositeIdParent {
            
            /// <summary>
            /// Query helper for member CompositeIdParent.Id
            /// </summary>
            public static OrderByClause Id {
                get {
                    return new OrderByClause("Id");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// <summary>
        /// Query helper for member ProjectBy.CompositeIdParent
        /// </summary>
        public partial class CompositeIdParent {
            
            /// <summary>
            /// Query helper for member CompositeIdParent.Id
            /// </summary>
            public static PropertyProjectionBuilder Id {
                get {
                    return new PropertyProjectionBuilder("Id");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// <summary>
        /// Query helper for member GroupBy.CompositeIdParent
        /// </summary>
        public partial class CompositeIdParent {
            
            /// <summary>
            /// Query helper for member CompositeIdParent.Id
            /// </summary>
            public static NHibernate.Criterion.IProjection Id {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Id");
                }
            }
        }
    }
}
