using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("RhinoIglooSample.Web for Microsoft .NET Framework 3.5")]
[assembly: AssemblyDescriptionAttribute("Rhino Commons - Support and extension for many advance usecases")]
[assembly: AssemblyCompanyAttribute("Rhino Tools Project")]
[assembly: AssemblyProductAttribute("RhinoIglooSample.Web")]
[assembly: AssemblyCopyrightAttribute("Rhino Tools Project, original author or authors")]
[assembly: AssemblyVersionAttribute("2.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0.1219")]
[assembly: AssemblyFileVersionAttribute("2.0.0.1219")]
[assembly: AssemblyDelaySignAttribute(false)]

#if MONO
[assembly: AssemblyKeyFileAttribute(@"C:\OSS\Rhino.Tools\ayende-open-source.snk")]
#endif
