copy C:\oss\rhino-tools\build\net-3.5\debug\Castle.Core.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Castle.Core.xml
copy C:\oss\rhino-tools\build\net-3.5\debug\Castle.DynamicProxy.license.txt
copy C:\oss\rhino-tools\build\net-3.5\debug\Castle.DynamicProxy2.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Castle.DynamicProxy2.xml
copy C:\oss\rhino-tools\build\net-3.5\debug\Castle.MicroKernel.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Castle.MicroKernel.xml
copy C:\oss\rhino-tools\build\net-3.5\debug\Castle.Windsor.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Castle.Windsor.xml
copy C:\oss\rhino-tools\build\net-3.5\debug\Iesi.Collections.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Iesi.Collections.license.txt
copy C:\oss\rhino-tools\build\net-3.5\debug\Iesi.Collections.pdb
copy C:\oss\rhino-tools\build\net-3.5\debug\Iesi.Collections.Test.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Iesi.Collections.Test.pdb
copy C:\oss\rhino-tools\build\net-3.5\debug\Iesi.Collections.xml
copy C:\oss\rhino-tools\build\net-3.5\debug\list.cmd
copy C:\oss\rhino-tools\build\net-3.5\debug\log4net.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\log4net.license.txt
copy C:\oss\rhino-tools\build\net-3.5\debug\log4net.xml
copy C:\oss\rhino-tools\build\net-3.5\debug\Lucene.Net.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Lucene.Net.xml
copy C:\oss\rhino-tools\build\net-3.5\debug\NHibernate.Caches.SysCache.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\NHibernate.Caches.SysCache.pdb
copy C:\oss\rhino-tools\build\net-3.5\debug\NHibernate.Caches.SysCache.Tests.pdb
copy C:\oss\rhino-tools\build\net-3.5\debug\NHibernate.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\NHibernate.pdb
copy C:\oss\rhino-tools\build\net-3.5\debug\NHibernate.Search.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\NHibernate.Search.pdb
copy C:\oss\rhino-tools\build\net-3.5\debug\NHibernate.Test.pdb
copy C:\oss\rhino-tools\build\net-3.5\debug\NHibernate.XML
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Commons.Clr.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Commons.Clr.pdb
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Commons.Clr.xml
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Commons.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Commons.NHibernate.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Commons.NHibernate.pdb
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Commons.NHibernate.xml
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Commons.pdb
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Commons.xml
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Mocks.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Mocks.xml
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Security.dll
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Security.pdb
copy C:\oss\rhino-tools\build\net-3.5\debug\Rhino.Security.xml