//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Rhino")]
[assembly: AssemblyCopyright("Oren Eini (c) 2006")]
[assembly: AssemblyDescription("Rhino.Testin")]
[assembly: AssemblyInformationalVersion("1.0.736")]
[assembly: AssemblyTitle("Rhino.Testin")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("1.0.736")]


